### ISSUE TITLE
Add Bubbles Effect

### ISSUE THREAD

**Issue by BabyElias** [Anjuli08/Creative-CSS-Effects#1]
I would like to add moving bubbles effect using HTML & CSS

**Comment by Divyanshi2408** [comment]
Hey @Anjuli08  I want to add bubble efect Could you please assign me

**Comment by Anjuli08** [comment]
> I would like to add moving bubbles effect using HTML & CSS

sure! go ahead

**Comment by Anjuli08** [comment]
> Hey @Anjuli08 I want to add bubble efect Could you please assign me

hey! you can work on other issue or create a new one as it is assigned on first come first serve basis

**Comment by EbrG786** [comment]
@Anjuli08 Please add these tags hacktoberfest hacktoberfest-accepted hacktoberfest2022 since the repository is not included in it.
