### ISSUE TITLE
Bubbles Effects Layout Issue

### ISSUE THREAD

**Issue by louierosero** [Anjuli08/Creative-CSS-Effects#13]
# Issue Preview
![issue1](https://user-images.githubusercontent.com/5468245/194744067-ef9c391d-4dbc-4758-b84b-cd7e73367338.JPG)

## Issue Description
There is a Scroll Effects on both VERTICAL and HORIZONTAL which is really don't need for this Single Page.

**Comment by Anjuli08** [comment]
you can work on this!
