### ISSUE TITLE
Animation CSS background issue

### ISSUE THREAD

**Issue by yjwhy** [Anjuli08/Creative-CSS-Effects#18]
![image](https://user-images.githubusercontent.com/86042155/194747687-5137b200-19f9-4a06-89d9-38ee73e22a88.png)

I can make the background non-repeat if you want. ; >

**Comment by Anjuli08** [comment]
sure! you can work on it

**Comment by yjwhy** [comment]
Created the PR #66 for this issue!

**Comment by nidhish-srivastava** [comment]
1.The background is still having problem ---->  can i fix it @Anjuli08 
![Screenshot (14)](https://user-images.githubusercontent.com/108972571/195606868-89bc0f19-f220-4377-8aea-958c450ff3be.png)
2.2.I can make the  the buttons more attractive
3.I can improve the layout inside the login card as well
