### ISSUE TITLE
CSS Raindrops Animation

### ISSUE THREAD

**Issue by MonalikaPatnaik** [Anjuli08/Creative-CSS-Effects#21]
Hey!! I would like to create raindrops falling over the camera/screen effect using css.

**Comment by kalaSriSaiRaksha** [comment]
please assign me this issue

**Comment by Anjuli08** [comment]
> Hey!! I would like to create raindrops falling over the camera/screen effect using css.

go ahead!

**Comment by Anjuli08** [comment]
> please assign me this issue

The effect is not visible!

**Comment by kalaSriSaiRaksha** [comment]
I created you can see that

**Comment by kalaSriSaiRaksha** [comment]
I just sent you a pull request you can see that please verify it

**Comment by kalaSriSaiRaksha** [comment]
i just updated
