### ISSUE TITLE
Css Card Animation

### ISSUE THREAD

**Issue by Morbius00** [Anjuli08/Creative-CSS-Effects#22]
![Open Source Love](https://badges.frapsoft.com/os/v1/open-source.svg?v=103)

## Css Card Animation
Want to make a beautiful html and Css card with animation .
please assigned me for it.
regards,

**Comment by Anjuli08** [comment]
go ahead!

**Comment by KrishnaChaitanya1822** [comment]
Can I work on it?

**Comment by Morbius00** [comment]
> Can I work on it?

The issue is already fix by me and I made the PR ..
