### ISSUE TITLE
Css Motion animation

### ISSUE THREAD

**Issue by sumitbaroniya** [Anjuli08/Creative-CSS-Effects#24]
Please assign me this issue

**Comment by Anjuli08** [comment]
pls specify what are you going to do in it!

**Comment by sumitbaroniya** [comment]
![1](https://user-images.githubusercontent.com/75536160/194762429-cbe1623f-d23b-439c-b95f-acd53f991032.PNG)
![2](https://user-images.githubusercontent.com/75536160/194762433-2c63351a-fffc-42f8-a1b6-2ed137d0b568.PNG)
![3](https://user-images.githubusercontent.com/75536160/194762435-679398fa-c72b-4374-b989-035a699448e9.PNG)

**Comment by sumitbaroniya** [comment]
These beautiful circles moving up and down together which looks so beautiful and attractive.

**Comment by Anjuli08** [comment]
ok! you can work on this issue
