### ISSUE TITLE
Css Meditative Breathing

### ISSUE THREAD

**Issue by sumitbaroniya** [Anjuli08/Creative-CSS-Effects#35]
Please assign me this issue under hacktoberfest

**Comment by yosaami** [comment]
hey @Anjuli08 , I have created a PR, for meditative breathing.
I have created this meditation app using CSS, HTML and JavaScript.
Clicking on the 'begin' option begins the breathing process.
It has an option to select the number of breaths and counter for the remaining breaths.
![Screenshot (22)](https://user-images.githubusercontent.com/76916269/194763970-da6d7fd4-cf3c-44ab-898d-766855317fd8.png)

**Comment by sumitbaroniya** [comment]
@yosaami i have created this issue and i am working on it so please look another issue.

**Comment by Anjuli08** [comment]
> hey @Anjuli08 , I have created a PR, for meditative breathing. I have created this meditation app using CSS, HTML and JavaScript. Clicking on the 'begin' option begins the breathing process. It has an option to select the number of breaths and counter for the remaining breaths. ![Screenshot (22)](https://user-images.githubusercontent.com/76916269/194763970-da6d7fd4-cf3c-44ab-898d-766855317fd8.png)

this is not working! either you both can coordinate accordingly. so I'm assigning to both of you

**Comment by yosaami** [comment]
I have updated the code, although its working on my device, please check and let me know if it needs changes.

**Comment by 0xYashwanth** [comment]
Hey @Anjuli08, I have a pretty decent knowledge of HTML & CSS, and I want to contribute to the Meditative breathing project.
Could you please assign this to me?
Thanks for reading!

**Comment by Anjuli08** [comment]
this is already done! you can work on other issues.
