### ISSUE TITLE
Animated Card Layout

### ISSUE THREAD

**Issue by louierosero** [Anjuli08/Creative-CSS-Effects#55]
# Project Preview
![Animated Card Layout](https://user-images.githubusercontent.com/5468245/194900370-9d2d5236-6be8-4f05-be65-b38eb6b6732c.gif)

## Project Description
An animated Card Layout that when you hover on it. It will float with a shadow and have a button.

**Comment by Anjuli08** [comment]
you can work on it

**Comment by Anjuli08** [comment]
Thankyou for contributing to this repo
