### ISSUE TITLE
Timeline using Html & CSS

### ISSUE THREAD

**Issue by samipak458** [Anjuli08/Creative-CSS-Effects#61]
To create an issue, edit this template to fill your details as well as describe your issue and then post it.
**add 'x' to the relevant to define you**
- [X] Hacktoberfest Participant  
- [X] Contributor

**Is your feature request related to a problem? Please describe.**
I would like to add my small project which is basically a **timeline** section. 

**Desktop View**
![image](https://user-images.githubusercontent.com/52650290/194935055-260ca6cf-49ea-4a15-9f37-a889af6a09e0.png)

**Mobile View**
![image](https://user-images.githubusercontent.com/52650290/194935607-dcdaf88f-3e22-4ce6-971a-11957dd39f43.png)

**Describe the solution you'd like**
A Timeline project that is easy to use and helps learners understand the basic concept of CSS by implementing it. I used all the basic CSS and media queries to make the timeline project,

**Additional context**
I think these help the beginners in better understanding of website designing.

**Comment by samipak458** [comment]
@Anjuli08 kindly assign this issue to me.

**Comment by Anjuli08** [comment]
pls go ahead!
