### ISSUE TITLE
3D-Text-Animation

### ISSUE THREAD

**Issue by MonalikaPatnaik** [Anjuli08/Creative-CSS-Effects#67]
To create an issue, edit this template to fill your details as well as describe your issue and then post it.
**add 'x' to the relevant to define you**
- [ 'x'] Hacktoberfest Participant  
- ['x' ] Contributor

**Is your feature request related to a problem? Please describe.**
Hey!! I would like to create a 3D text animation using html and css..
Thanks!!

**Comment by MonalikaPatnaik** [comment]
Hey!! Kindly assign me this issue so that I can start working on it @Anjuli08

**Comment by Anjuli08** [comment]
text animation is already done! can you suggest any other design
