### ISSUE TITLE
Add  sign Up page

### ISSUE THREAD

**Issue by Divyanshi2408** [Anjuli08/Creative-CSS-Effects#7]
hey @Anjuli08 I want to add a sign up page

**Comment by Divyanshi2408** [comment]
Could you please assign me

**Comment by Anjuli08** [comment]
> hey @Anjuli08 I want to add a sign up page

hey! please mention a little details that you want to add in the page. I'll assign it to you!

**Comment by yashgithub2021** [comment]
Hey @Anjuli08, can you assign this issue to me?

**Comment by rajatrai30** [comment]
hello @Anjuli08 
I can easily contribute for this issue.
assign this task to me.

**Comment by Divyanshi2408** [comment]
> > hey @Anjuli08 I want to add a sign up page
> 
> hey! please mention a little details that you want to add in the page. I'll assign it to you!

@Anjuli08 I will attach  the signup page in the login page, if someone wants to create a new account, then they can use the signup page.

**Comment by manishgupta416** [comment]
Can you assign to me?

**Comment by Anjuli08** [comment]
> > > hey @Anjuli08 I want to add a sign up page
> > 
> > 
> > hey! please mention a little details that you want to add in the page. I'll assign it to you!
> 
> @Anjuli08 I will attach the signup page in the login page, if someone wants to create a new account, then they can use the signup page.

go ahead! and create it in a new file

**Comment by Anjuli08** [comment]
> Can you assign to me?

hey, it is on first come first serve basis!  you can work other issue till then.

**Comment by AditiBendre** [comment]
Hii
Starting to work on this issue. Will send a PR today.

**Comment by Divyanshi2408** [comment]
> > > > hey @Anjuli08 I want to add a sign up page
> > > 
> > > 
> > > hey! please mention a little details that you want to add in the page. I'll assign it to you!
> > 
> > 
> > @Anjuli08 I will attach the signup page in the login page, if someone wants to create a new account, then they can use the signup page.
> 
> go ahead! and create it in a new file

okay

**Comment by sumitbaroniya** [comment]
Please assign me this issue.

**Comment by Upasana-Roy** [comment]
Hello, I am interested to work on this issue. Please assign it to me.
