### ISSUE TITLE
BMI Calculator

### ISSUE THREAD

**Issue by mayuri-agrawal** [Anjuli08/Creative-CSS-Effects#70]
To create an issue, edit this template to fill your details as well as describe your issue and then post it.
**add 'x' to the relevant to define you**
- [x] Hacktoberfest Participant  
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

•I want to add a  JavaScript-based project to this repository , BMI calculator.
•In this project i'will be covering the basics of javascript.
•Kindly assign this issue to me. Thank you😊

**Comment by Anjuli08** [comment]
pls go ahead!
