### ISSUE TITLE
CSS Background synced hover menu

### ISSUE THREAD

**Issue by Anubhavgupta18** [Anjuli08/Creative-CSS-Effects#72]
- [x] Hacktoberfest Participant  

I want to add a CSS based project to this repository. The project is called Background synced hover menu.

![Screenshot (8)](https://user-images.githubusercontent.com/96951519/195377306-2ed6152c-edea-456b-a0bf-33e22b109522.png)
![Screenshot (9)](https://user-images.githubusercontent.com/96951519/195377354-c0895907-1305-4a69-b7d8-c9a72c8c4e86.png)

**Comment by Anjuli08** [comment]
pls go ahead!

**Comment by Anjuli08** [comment]
pls go ahead!
